Add web ml pipeline guide
rwalczyna/tizen-docs pull request #4
Opened 2021-03-22 15:06 UTC by pwasowski2

### Change Description ###

Add guide for Tizen Web ML Pipeline API

### API Changes ###

 - ACR: TWDAPI-274

2021-03-23 09:06 UTC, rwalczyna requested changes

2021-03-23 09:06 UTC, rwalczyna commented on docs/application/web/guides/machine-learning/pipeline.md
> +You can use some of the standard GStreamer and NNStreamer elements (also called _nodes_ througout this guide) in your applications.
```suggestion
You can use some of the standard GStreamer and NNStreamer elements (also called _nodes_ throughout this guide) in your applications.
```

2021-03-23 09:06 UTC, rwalczyna commented on docs/application/web/guides/machine-learning/pipeline.md
> +2. Call `tizen.ml.pipeline.createPipeline()` method:
https://github.com/rwalczyna/tizen-docs/pull/3#discussion_r597558980
We don't use the term method or function in the guides hence, request you to remove it.

```suggestion
2. Call `tizen.ml.pipeline.createPipeline()`:
```
check whole file

2021-03-23 09:06 UTC, rwalczyna commented on docs/application/web/guides/machine-learning/pipeline.md
> +Check API reference (for [mobile](../../api/latest/device_api/mobile/tizen/ml_pipeline.html), [wearable](../../api/latest/device_api/wearable/tizen/ml_pipeline.html), and [tv](../../api/latest/device
```suggestion
Check API reference (for [mobile](../../api/latest/device_api/mobile/tizen/ml_pipeline.html#PipelineState), [wearable](../../api/latest/device_api/wearable/tizen/ml_pipeline.html#PipelineState), and [tv](../../api/latest/device_api/tv/tizen/ml_pipeline.html#PipelineState) applications) to see how pipelines transition between different states.
```

2021-03-23 09:06 UTC, rwalczyna commented on docs/application/web/guides/machine-learning/pipeline.md
> +Pipeline API allows registering listeners triggered by pipeline state changes and polling current pipeline state.
Consider unifying style with line 2. (allows)

2021-03-23 09:06 UTC, rwalczyna commented on docs/application/web/guides/machine-learning/pipeline.md
> +
Please unify style of list. One time you use empty lines and another you don't.

2021-03-23 09:06 UTC, rwalczyna commented on docs/application/web/guides/machine-learning/pipeline.md
> +Newly created pipeline transitions through `READY` to `PAUSED` state - you have to manually start it to set it in `PLAYING` state.
```suggestion
Newly created pipeline transitions through `READY` to `PAUSED` state - you have to manually start it to set it to `PLAYING` state.
```

2021-03-23 09:06 UTC, rwalczyna commented on docs/application/web/guides/machine-learning/pipeline.md
> +1. Call its `start()` method:
```suggestion
1. To start data flow within a pipeline call its `start()` method:
```

2021-03-23 09:06 UTC, rwalczyna commented on docs/application/web/guides/machine-learning/pipeline.md
> +To start data flow within a pipeline:
```suggestion
```

2021-03-23 09:06 UTC, rwalczyna commented on docs/application/web/guides/machine-learning/pipeline.md
> +3. Now you can read the current value of `pattern` property. Use the property type defined in `gst-launch-1.0` output:
What is `gst-launch-1.0`? You didn't write anything about it.

2021-03-23 09:06 UTC, rwalczyna commented on docs/application/web/guides/machine-learning/pipeline.md
> +   > [!Note] You can also set the `pattern` value in pipeline description:
```suggestion
   > **Note** You can also set the `pattern` value in pipeline description:
```

2021-03-23 09:06 UTC, rwalczyna commented on docs/application/web/guides/machine-learning/pipeline.md
> +You can read the tensors output by the pipeline with the application code by registering a callback, triggered by data coming into `appsink` or `tensor_sink`.
Can you write some details about `appsink` and `tensor_sink`?

2021-03-23 09:06 UTC, rwalczyna commented on docs/application/web/guides/machine-learning/pipeline.md
> +![Pipeline with branches and a switch](./media/pipeline_with_switch.svg)
Please add empty line before image.

2021-03-23 09:06 UTC, rwalczyna commented on docs/application/web/guides/machine-learning/pipeline.md
> +   > [!NOTE]
```suggestion
   > **Note**
```
please check whole file

2021-03-23 09:06 UTC, rwalczyna commented on docs/application/web/guides/machine-learning/pipeline.md
> +   > Sending data between between `CustomFilter` running in JS application and GStreamer pipeline has large overhead.
```suggestion
   > Sending data between `CustomFilter` running in JS application and GStreamer pipeline has large overhead.
```

2021-03-23 12:23 UTC, pwasowski2 commented on docs/application/web/guides/machine-learning/pipeline.md
> +   > [!Note] You can also set the `pattern` value in pipeline description:
According to the style guide, we should use the "[!Note]" syntax: https://github.com/Samsung/tizen-docs/pull/1284#discussion_r505167050

When I was updating guides for Bluetooth, HQ reviewers requested to change the syntax to the one I used here: https://github.com/Samsung/tizen-docs/pull/1284#discussion_r505167050

2021-03-23 12:24 UTC, pwasowski2 commented on docs/application/web/guides/machine-learning/pipeline.md
> +   > [!NOTE]
According to the style guide, we should use the "[!Note]" syntax: https://github.com/Samsung/tizen-docs/pull/1284#discussion_r505167050

When I was updating guides for Bluetooth, HQ reviewers requested to change the syntax to the one I used here: https://github.com/Samsung/tizen-docs/pull/1284#discussion_r505167050

I will leave it as it is.

2021-03-23 12:34 UTC, pwasowski2 commented on docs/application/web/guides/machine-learning/pipeline.md
> +2. Call `tizen.ml.pipeline.createPipeline()` method:
I'll do it 👍

2021-03-23 13:40 UTC, pwasowski2 commented on docs/application/web/guides/machine-learning/pipeline.md
> +Pipeline API allows registering listeners triggered by pipeline state changes and polling current pipeline state.
I am not sure, if I got it right, did you mean a change like this one:

```suggestion
Pipeline API allows to register listeners triggered by pipeline state changes and polling current pipeline state.
```

2021-03-23 13:43 UTC, pwasowski2 commented on docs/application/web/guides/machine-learning/pipeline.md
> +
I'll fix it in the update commit. I hope it'll be consistent then.

2021-03-23 13:43 UTC, rwalczyna commented on docs/application/web/guides/machine-learning/pipeline.md
> +Pipeline API allows registering listeners triggered by pipeline state changes and polling current pipeline state.
Yes, but you also need to change a form of second verb (polling -> to poll)

2021-03-23 13:46 UTC, pwasowski2 commented on docs/application/web/guides/machine-learning/pipeline.md
> +1. Call its `start()` method:
I'll do it in the update commit, only omitting "method".

2021-03-23 13:47 UTC, pwasowski2 commented on docs/application/web/guides/machine-learning/pipeline.md
> +To start data flow within a pipeline:
I'll do it in the update commit.

2021-03-23 13:49 UTC, pwasowski2 commented on docs/application/web/guides/machine-learning/pipeline.md
> +3. Now you can read the current value of `pattern` property. Use the property type defined in `gst-launch-1.0` output:
My fault - I have meant `gst-inspect-1.0`. I'll fix it in the update commit.

2021-03-23 13:49 UTC, pwasowski2 commented on docs/application/web/guides/machine-learning/pipeline.md
> +![Pipeline with branches and a switch](./media/pipeline_with_switch.svg)
Ok 👍

2021-03-23 14:03 UTC, pwasowski2 commented on docs/application/web/guides/machine-learning/pipeline.md
> +Pipeline API allows registering listeners triggered by pipeline state changes and polling current pipeline state.
Ok 👍

2021-03-23 14:07 UTC, pwasowski2 commented on docs/application/web/guides/machine-learning/pipeline.md
> +You can read the tensors output by the pipeline with the application code by registering a callback, triggered by data coming into `appsink` or `tensor_sink`.
Unfortunately, I am no expert in nnstreamer/gstreamer - I will add a line suggesting users to read the documentation in gst-inspect-1.0.

2021-03-24 07:49 UTC, rwalczyna approved these changes

2021-03-25 12:40 UTC, TomaszLukawskiSam reviewed
Looks good to me.

2021-03-26 09:16 UTC, TomaszLukawskiSam approved these changes
Looks good to me.

2021-04-20 12:30 UTC, closed without merging